repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/ikamensh/flynt/
    rev: '1.0.1'
    hooks:
      - id: flynt
        language_version: python3.10
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py3-plus --py36-plus --py37-plus --py38-plus --py39-plus
        language_version: python3.10
  - repo: https://github.com/myint/autoflake
    rev: 'v1.4'
    hooks:
      - id: autoflake
        args: ['--remove-all-unused-imports', '-i']
        language_version: python3.10
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.10
